
title: Blog
email: your-email@example.com
description: Hello! 
destination: docs
baseurl: "/jekyll-project" 
url: "" 
twitter_username: vachev
github_username:  valentinvachev

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
